src/components/DataTable/index.js
Lables now show instead of full urls for ingest, portal, and globus
Amount of datasets/uploads currently selected now displays
=> Lables now show instead of full urls for ingest, portal, and globus

src/components/DataTable/index.js, src/styles/globals.css
where aggregate data will eventually be
=> Tweaked wording of count to "___ selected" and moved it to the right

src/components/DataTable/index.js
Globus url for uploads will not NOT display if it is in the reorganized 
state.
=> Globus url for uploads will not NOT display if it is in the reorganized

src/pages/_app.js
Bug was caused by a css order of execution issue. In a previous update, I had changed the order in which css was being imported. This seems to have messed up some formatting. This bad change has been reverted
=> Fixed bug causing alignment issue with buttons.

src/components/DataTable/index.js, src/pages/index.js, src/styles/globals.css
Moved the count down to match the pagination ui vertically. Fixed an alignment issue with the switch and clear buttons.
=> Derek furst/fix bad auth

src/components/DataTable/index.js
Fixed count-inconsistency when applying filters via query params. Fixed issue when setting organ filter via query param. Changed all instances of organ_types to organ.
=> Derek furst/fix counts

src/components/DataTable/index.js, src/package-lock.json, src/package.json, src/pages/index.js, src/styles/globals.css
Implemented export csv functionality. Misc visual tweaks and alignments.
=> Derek furst/version 2

src/pages/index.js
Removed link from the hubmap logo
=> removed the link on hubmap logo

src/components/DataTable/index.js
Fixed an irregularity when generating data ingest links.
=> Added 'browse/' to the Data portal link.

src/context/AppContext.jsx
Change log:
1. Updated the logic so that the react state of isAuthenticated is set to false explicitly when the cookies are deleted.
=> Update authentication expiration logic

src/context/AppContext.jsx
Change log:
1. Send the user back to Globus logout confirmation page.
=> Redirect user to globus logout confirmation page - #portal-ui/issues/982

src/context/AppContext.jsx, src/example.env, src/example.sennet.env, src/lib/helper.js
Replace NEXT_PUBLIC_UBKG_SAB with NEXT_PUBLIC_APP_CONTEXT
Add appContext to helper.js 
And Update the Document Title to use this new value
=> NEXT_PUBLIC_UBKG_SAB / NEXT_PUBLIC_APP_CONTEXT

src/components/DataTable/DatasetTable.jsx
Updates the has_metadata value for the dataset Table to use has_donor_metadata
=> Updates has_metadata to has_donor_metadata

hubmap-docker/data-ingest-board/Dockerfile, sennet-docker/data-ingest-board/Dockerfile
=> Fix nodejs docker install

src/components/ModalOverData.jsx
Change log:
1. Remove revisions column from CSV
2. Add level color
=> Remove revision column from CSV

src/components/ModalOver.jsx
Change log:
1. Check that method exists
=> Check that method exists

src/components/DataTable/index.js, src/components/ModalOverData.jsx, src/lib/GoogleTagManager.js, src/lib/helpers/table.js
Change log:
1. Fix typo
2. Add new elements for tracking
Currently these are the list of things being tracked.
1. User clicks Search
2. User clicks Switch to Datasets/Uploads 
3. User clicks download CSV link on main page
4. User clicks download CSV button on processed dataset modal
5. User clicks to view particular entity dropdown
6. User submits to bulk process dataset
=> Fix typo, add more elements to be tracked - #187

src/components/DataTable/DatasetTable.jsx, src/components/DataTable/UploadTable.jsx
Change log:
1. Resolve modal style in Uploads section
2. Fix call to modal
=> Fix theming and use updated mehtod name

jsconfig.json, src/jsconfig.json, src/next.config.js, src/pages/_app.js
Following merged PR #222 for PROD
=> Add '@' path alias for cleaner imports

src/components/DataTable/UploadTable.jsx, src/example.env, src/example.sennet.env, src/lib/helpers/envs.js
Change log:
1. Add exclusion functionality for uploads
=> Make exclude feature work for uploads also - #251

src/components/Visualizations/Charts/Sankey.jsx
Change log:
1. Pass token to sankey endpoint
=> Add Authorization to request - #264

src/pages/sankey.js
Change log:
1. Rearrange logic to wait for `globusToken`
=> Rearrange logic for waiting on globusToken

src/package.json, src/pages/sankey.js, src/public/css/xac-sankey.css, src/styles/xac-sankey.styl
Change log:
1. Filter hidden column
=> Can filter a hidden column - #270

src/components/DataTable/DatasetTable.jsx, src/components/DataTable/UploadTable.jsx, src/example.env, src/example.sennet.env, src/lib/helpers/general.js, src/lib/helpers/table.js
Change log:
1. Add Priority Project List column
After:
(When ingest-api card is completed will make this PR ready, but should work out the box.)
=> Update filtering for priorty project list field - #298

src/pages/_document.js
Change log:
1. Put back script links to top before NextScript
=> Revert change due to Addons undefined error - #285

src/components/DataTable/DatasetTable.jsx, src/lib/helpers/table.js
Change log:
1. Add selectors for cypress tests
=> Add selector for testing purposes - #315

src/package.json, src/public/css/xac-sankey.css, src/styles/xac-sankey.styl
=> Bump xac-sankey version

src/components/DataTable/UploadTable.jsx
Change log:
1. Fix reference error caused by refactor
=> Fix uploads bug - #315

src/components/DataTable/index.js
=> Add null check

src/lib/helpers/table.js
Change log:
1. Escape any field for csv
=> Apply escape for any field - #347
